### ISSUE TITLE
retention policy gets ignored. old snapshots not getting deleted

### ISSUE THREAD

**Issue by xxharjinder** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#13]
These are the only changes I have made 

```
autosnapshots="yes" # set to "yes" to have script auto snapshot your source dataset. Set to "no" to skip snapshotting.
snapshot_hours="0"
snapshot_days="3"
snapshot_weeks="0"
snapshot_months="0"
snapshot_years="0"
replication="none"
```
The snapshots get created fine but they not being deleted after 3 days.

**Comment by edchristoph** [comment]
Same here, 
I dit not make any changes to the default snapshot retention policy and syncoid_mode="strict-mirror".
Autosnaphot on the source dataset works as expecte such that it only keeps the 7 most recent daily snapshots.
However, zfs replication to the destination dataset keeps all the daily snapshots created since I started using this script on 25 Aug. 

I let the script write syncoid_flags actually used for the replicationto the log:  syncoid_flags: -r --force-delete
So that seems to be correct.
Any idea what's gong wring here?

**Comment by bclinton1** [comment]
Just looked and I see the same. Set for 5 days daily and I have 11 days so far.

**Comment by kim0sabe** [comment]
yep ,, also seeing the same behaviour ,, fine on the source but the replication target doesnt seem to be removing snapshots

**Comment by SpaceinvaderOne** [comment]
Thanks for bringing this to my attention. I will have a look and see why this is happening and update the script. I should have time to look at this next week :)

**Comment by wadernat0rz** [comment]
I am also having the same issue - backups in the destination are not being deleted despite sync mode being set to 'strict-mirror'

**Comment by Gex2501** [comment]
ditto

**Comment by Frazzer951** [comment]
I read through syncoid's docs, and `--force-delete` will only delete whole datasets, if they are removed from the source directory. If you want to delete snapshots that no longer exist on the source, you need to also pass the flag `--delete-target-snapshots`

**Comment by Cryoforever** [comment]
Unfortunately this didn't seem to fix and most of  comments on the link pull request  show that most people are still having the same issue. the source is good and the destination gathers extra daily snapshots and the count just goes up.  I am still holding out hope that space invader will have a look :)

**Comment by wadernat0rz** [comment]
> > Unfortunately this didn't seem to fix and most of comments on the link pull request show that most people are still having the same issue. the source is good and the destination gathers extra daily snapshots and the count just goes up. I am still holding out hope that space invader will have a look :)
> 
> It only keep a single extra daily snapshot. I'm 99% sure this could be solved by adjusting the order of the function at the bottom of the script. I think if you have the prune function run before replication you won't get the extra snapshot.

I believe you are correct. I was looking at the script and the Syncoid documentation in more detail earlier and that's the conclusion I reached, as well. I changed the order on one of my instances and will see what happens during tomorrow morning's scheduled run.

**Comment by Cryoforever** [comment]
I have changed my order as well to see what happens tomorrow in the AM. I did not prune anything manually as I want to see if it clears them out.  Thank you both . I will report back

**Comment by Scott-St** [comment]
It should be the order as its ZFS replicating to the backup location then its running the prune so your getting any snapshots that are to be pruned at the destination before they are pruned.  Maybe that's by design?  But if you want them exactly in sync set the prune to run before the sync.

`#
########################################
#
# run the above functions 
pre_run_checks
create_sanoid_config
autosnap
rsync_replication
zfs_replication
autoprune`

Set it in this order to keep both copies the same. (I also re-arranged rsync in case anyone uses that as it will be the same issue)
`#
########################################
#
# run the above functions 
pre_run_checks
create_sanoid_config
autosnap
autoprune
rsync_replication
zfs_replication
`

**Comment by Cryoforever** [comment]
Success here for me after changing the order. Fantastic !

**Comment by gaming09** [comment]
> pre_run_checks
> create_sanoid_config
> autosnap
> autoprune
> rsync_replication
> zfs_replication

i changed the order at the bottom of the script to 
pre_run_checks
create_sanoid_config
autosnap
autoprune
rsync_replication
zfs_replication

but it doesnt seem to be pruning, do i have to manually remove the current snapshots first?

**Comment by wadernat0rz** [comment]
Do you also have the proper flags set for strict mirroring, [as seen in this post](https://github.com/SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications/pull/18#issuecomment-1728533196)?

**Comment by gaming09** [comment]
> Do you also have the proper flags set for strict mirroring, [as seen in this post](https://github.com/SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications/pull/18#issuecomment-1728533196)?

I missed that, thank you that worked 
added this at line 340
syncoid_flags+=("--delete-target-snapshots")

added this order at the bottom at line 479

pre_run_checks
create_sanoid_config
autosnap
autoprune
rsync_replication
zfs_replication

that seems to have done the trick, thank you

**Comment by Cryoforever** [comment]
well the number of snapshots  matches today for the source and destination but 4 of the items in APPDATA  didnt remove some of the dailies and not some of the others (see image). yesterday AND MOST DAYS they all removed no issue so same count  haha I have seen before in the last 3 weeks where some things pruned out where other did not but i figured it was the other issue.. I dont know .. hopefully Spaceinvader decides a plugin will be something he would like to do like he suggested. I am pretty sure  all the people would embrace the ease of a plugin instead.. It's a great idea this script but kind of a headache
![no match](https://github.com/SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications/assets/146344714/a287aea7-1e2c-43fe-82e5-2b81d3d84a94)
