### ISSUE TITLE
Address Database-Corruption in the script and also add a disclaimer in the corresponding yt-video

### ISSUE THREAD

**Issue by madejackson** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#15]
Thanks for this awesome Script. Important question:

Did you and how did you solve the issue with database-corruption?

When doing a snapshot of a live database (fe. sqlite3 for radarr, sonarr etc), the snapshop holds a version of a possibly corrupt database and hence is possibly useless: https://www.google.com/search?q=sqlite+zfs+snapshot

**Comment by madejackson** [comment]
Ok, So somebody run into this the hard way on reddit. I won't post the link as I am against using reddit.

I think SpaceinvaderOne should update his video to address this specific issue. Otherwise newbies won't have any recoverable backups.

**Comment by Octopusprime83** [comment]
I have a solution for this that perhaps you could incorporate into the script, so its a couple things, First create a variable to call a "does docker container DB?" function. Add this as  part of the precheck the code would be "docker stop $(docker ps -a -f label=zfs_snap_stop=yes)". This will check all dockers for the label key/value pair of key = "zfs_snap_stop" with value of "yes" and stop it. Then after snaps have been created add a "docker start $(docker ps -a -f label=zfs_snap_stop=yes" to the be used post snaps. 


In this way we can start/ stop containers with DB's with this script by simply applying labels to them (feel free the change the label to whatever you want). This should allow the pending changes to be written to the DB on container shutdown to avoid the DB and changes in ram from getting out of sync due to snapshotting. This issue is especially bad when nextcloud is working with a MS SQL or MYSQL DB backend.

**Comment by SpaceinvaderOne** [comment]
Yes thats a great idea to add a label to various containers. I will implement that for sure.
For nextcloud etc i am a big fan of using a dedicated database backup solution so database doesnt need to be shutdown
or example db-backup  which you can find on CA This can backup multiple DB bervers (Influx, Maria/Mysql/Mongo/Postgres/Redis/Rethink)

**Comment by Jarikk** [comment]
> This issue is especially bad when nextcloud is working with a MS SQL or MYSQL DB backend.

Hi. At least for MySQL/MariaDB database containers I've added a new functionality to the script - please check my PR #21.

**Comment by fent** [comment]
was this ever implemented?
