### ISSUE TITLE
rsync incremental backup instead of full backup

### ISSUE THREAD

**Issue by matlantin** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#2]
Hello Ed and thank you very much for your script, I'm using it successfully on my unRAID system to back up the appdata datasets to a remote NAS (through SMB).

As my backup destination has no ZFS, I'm using rsync.

I just noticed that your script always makes a full backup. Would it be possible to implement incremental backup when using rsync?

Many thanks,

**Comment by SpaceinvaderOne** [comment]
Hi @matlantin . 
I've made significant updates to the script, introducing the option that you asked for. You can now do either an rsync clone or an incremental rsync backup. Due to the unique structure of ZFS datasets, iterating through child datasets to achieve rsync hardlinking was challenging. This is because each child dataset operates as a distinct filesystem, so needing separate rsync jobs for each child dataset.
However at last :), I've successfully done this. When you set the rsync type to "incremental", the script will create a directory named after the source pool and dataset. Inside this directory, a folder bearing a date and timestamp will be generated, housing all child folders and their respective contents. On subsequent runs, a new dated folder will be created for the incremental backup, but it will leverage hardlinks to share common data, ensuring space efficiency.

**Comment by matlantin** [comment]
Thanks for the nice job !
